# Generated by Django 3.1.2 on 2020-12-11 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='file/uploads/', verbose_name='فایل')),
                ('name', models.CharField(default='UNKNOWN', max_length=300, verbose_name='نام فایل')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='حجم فایل')),
            ],
            options={
                'verbose_name': 'فایل',
                'verbose_name_plural': 'فایل\u200cها',
            },
        ),
    ]
