REGISTER_TEMPLATE = 'gentellela/register.html'
REGISTER_CONFIMATION_TEMPLATE = 'gentellela/register_succeed.html'
FORGOT_PASSWORD_EMAIL_SENT_TEMPLATE = 'gentellela/email_sent.html'
RESET_PASSWORD_DONE_TEMPLATE = 'gentellela/reset_password_done.html'
GENERIC_MODEL_VIEW_TEMPLATE = 'generic_model_list.html'
GENERIC_MODEL_FORM_TEMPLATE = 'generic_model_form.html'
GENERIC_MODEL_MULIFORM_TEMPLATE = 'generic_model_multiform.html'
PROFILE_FORM_TEMPLATE = 'gentellela/profile_form.html'
AVATAR_MAX_SIZE = 2 * 1024 * 1024