# Generated by Django 3.1.2 on 2021-03-23 17:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Signal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signal_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ و زمان')),
                ('result_datetime', models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ و زمان پایان معامله')),
                ('asset', models.CharField(choices=[('EUR/AUD', 'Euraud'), ('EUR/USD', 'Eurusd'), ('EUR/GBP', 'Eurgbp'), ('USD/JPY', 'Usdjpy'), ('USD/CAD', 'Usdcad'), ('AUD/CHF', 'Audchf'), ('GBP/NZD', 'Gbpnzd'), ('BTC/USDT', 'Btcusdt'), ('ETH/USDT', 'Ethusdt'), ('TRX/USDT', 'Trxusdt'), ('ADA/USDT', 'Adausdt')], default='EUR/USD', max_length=10, verbose_name='دارایی')),
                ('trade_id', models.CharField(blank=True, help_text='مشخصه\u200cای که با آن بتوان معامله را در پلتفرم معاملاتی پیدا کرد', max_length=100, null=True, verbose_name='شناسه Trade')),
                ('entry_type', models.CharField(choices=[('خرید', 'Buy'), ('فروش', 'Sell')], default='خرید', max_length=4, verbose_name='نوع معامله')),
                ('entry_point1', models.DecimalField(decimal_places=6, max_digits=13, verbose_name='نقطه ورود اول')),
                ('entry_point2', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True, verbose_name='نقطه ورود دوم')),
                ('stop_loss1', models.DecimalField(decimal_places=6, max_digits=13, verbose_name='حد ضرر اول')),
                ('stop_loss2', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True, verbose_name='حد ضرر دوم')),
                ('take_profit1', models.DecimalField(decimal_places=6, max_digits=13, verbose_name='حد سود اول')),
                ('take_profit2', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True, verbose_name='حد سود دوم')),
                ('take_profit3', models.DecimalField(blank=True, decimal_places=6, max_digits=13, null=True, verbose_name='حد سود سوم')),
                ('risk_reward', models.FloatField(verbose_name='نسبت سود به ضرر')),
                ('result_pip', models.SmallIntegerField(default=0, verbose_name='سود/ضرر نهایی (پیپ)')),
                ('result_dollar', models.DecimalField(decimal_places=6, default=0, max_digits=13, verbose_name='سود/ضرر نهایی (دلار)')),
                ('lot', models.PositiveSmallIntegerField(default=0, verbose_name='حجم ورود')),
                ('mistakes', models.TextField(blank=True, null=True, verbose_name='اشتباهات معامله')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سیگنال',
                'verbose_name_plural': 'سیگنال\u200cها',
            },
        ),
    ]
