# Generated by Django 3.1.2 on 2021-03-23 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='entry_type',
            field=models.CharField(choices=[('buy', 'خرید'), ('sell', 'فروش')], default='buy', max_length=4, verbose_name='نوع معامله'),
        ),
    ]
