# Generated by Django 3.1.2 on 2021-03-23 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0002_auto_20210323_2247'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTAAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('any_news', models.BooleanField(default=False, help_text='در صورتی که در مدت معامله، خبری مرتبط با دارایی وجود دارد این گزینه را تیک بزنید', verbose_name='خبر؟')),
                ('news_detail', models.TextField(help_text='توجه: سه دقیقه قبل و بعد از خبر نباید وارد معامله شوید، اما در صورتی که برای انجام معامله مصر هستید، اطلاعات خبر را اینجا وارد کنید.', verbose_name='جزئیات خبر')),
                ('chart_move', models.CharField(choices=[('imp', 'Impulsive'), ('cor', 'Corrective')], max_length=3, verbose_name='حرکت نمودار')),
                ('impulsive_direction', models.CharField(blank=True, choices=[('up', 'صعودی'), ('dw', 'نزولی')], max_length=2, null=True, verbose_name='جهت روند')),
                ('zone_rejects', models.PositiveSmallIntegerField(help_text='تعداد برخورد و بازگشت قیمت از ناحیه را مشخص کنید ', verbose_name='مقاومت ناحیه')),
                ('pattern', models.CharField(blank=True, choices=[('up_tri', 'مثلث صعودی'), ('dw_tri', 'مثلث نزولی'), ('rct', 'مستطیل')], max_length=8, null=True, verbose_name='الگوی نمودار')),
                ('scenario', models.CharField(choices=[('sc1', 'سناریو شماره 1'), ('sc2', 'سناریو شماره 2'), ('sc3', 'سناریو شماره 3'), ('sc4', 'سناریو شماره 4'), ('sc5', 'سناریو شماره 5')], max_length=3, verbose_name='سناریو')),
                ('datetime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'استراتژی PTA',
                'verbose_name_plural': 'استراتژی\u200cهای PTA',
            },
        ),
    ]
