# Generated by Django 3.1.2 on 2021-03-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0003_ptaanalysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptaanalysis',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='pta_analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal', to='cfd.ptaanalysis', verbose_name='تحلیل PTA'),
        ),
    ]
