# Generated by Django 3.1.2 on 2021-03-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0005_auto_20210324_0006'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassicAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField(blank=True, help_text='توجه: سه دقیقه قبل و بعد از خبر نباید وارد معامله شوید، اما در صورتی که برای انجام معامله مصر هستید، اطلاعات خبر را اینجا وارد کنید.', null=True, verbose_name='اخبار')),
                ('major_trend', models.CharField(choices=[('bl', 'صعودی'), ('br', 'نزولی'), ('sd', 'رنج')], max_length=2, verbose_name='روند اصلی')),
                ('major_trend_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('major_trend_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
                ('intetrmediate_trend', models.CharField(choices=[('bl', 'صعودی'), ('br', 'نزولی'), ('sd', 'رنج')], max_length=2, verbose_name='روند میان\u200cمدت')),
                ('intetrmediate_trend_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('intetrmediate_trend_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
                ('pattern', models.CharField(choices=[('sy_tri', 'مثلث متقارن'), ('ds_tri', 'مثلث نزولی'), ('as_tri', 'مثلث صعودی'), ('ds_wdg', 'کنج نزولی'), ('as_wdg', 'کنج صعودی'), ('hd_sh', 'سر و شانه'), ('do_top', 'دو سقف'), ('do_btm', 'دو کف'), ('tr_top', 'سه سقف'), ('tr_btm', 'سه کف'), ('chnl', 'کانال'), ('flag', 'پرچم')], max_length=8, verbose_name='الگو')),
                ('pattern_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('pattern_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
                ('moving', models.TextField(verbose_name='میانگین متحرک')),
                ('moving_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('moving_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
                ('pivot', models.CharField(choices=[('d', 'روزانه'), ('w', 'هفتگی'), ('m', 'ماهیانه')], max_length=1, verbose_name='خطوط Pivot')),
                ('pivot_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('pivot_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
                ('fibo_correction', models.CharField(choices=[('74', '74%'), ('61', '61.8%'), ('50', '50%'), ('38', '38.2%'), ('23', '23.6%')], max_length=2, verbose_name='اصلاح فیبوناچی')),
                ('fibo_correction_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('fibo_target', models.CharField(choices=[('127', '127%'), ('150', '150%'), ('161', '161.8%'), ('200', '200%'), ('261', '261.8%'), ('423', '423.6%')], max_length=3, verbose_name='هدف فیبوناچی')),
                ('fibo_target_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('time_divergent', models.BooleanField(verbose_name='واگرایی زمانی')),
                ('time_divergent_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('time_divergent_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
                ('eliot', models.CharField(choices=[('wv1', 'موج اول'), ('wv2', 'موج دوم'), ('wv3', 'موج سوم'), ('wv4', 'موج چهارم'), ('wv5', 'موج پنجم'), ('wva', 'موج A'), ('wvb', 'موج B'), ('wvc', 'موج C')], max_length=3, verbose_name='موج\u200cهای الیوت')),
                ('eliot_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('candle', models.TextField(verbose_name='کندل\u200cشناسی')),
                ('candle_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('candle_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
                ('rsi_oversold', models.BooleanField(default=False, verbose_name='اشباع فروش در RSI')),
                ('rsi_overbought', models.BooleanField(default=False, verbose_name='اشباع خرید در RSI')),
                ('rsi_divergence', models.BooleanField(default=False, verbose_name='واگرایی در RSI')),
                ('rsi_hidden_divergence', models.BooleanField(default=False, verbose_name='واگرایی مخفی در RSI')),
                ('rsi_trend_breakout', models.BooleanField(default=False, verbose_name='شکست خط روند در RSI')),
                ('rsi_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('rsi_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
                ('momentum_oversold', models.BooleanField(default=False, verbose_name='اشباع فروش در Momentum')),
                ('momentum_overbought', models.BooleanField(default=False, verbose_name='اشباع خرید در Momentum')),
                ('momentum_divergence', models.BooleanField(default=False, verbose_name='واگرایی در Momentum')),
                ('momentum_hidden_divergence', models.BooleanField(default=False, verbose_name='واگرایی مخفی در Momentum')),
                ('momentum_trend_breakout', models.BooleanField(default=False, verbose_name='شکست خط روند در Momentum')),
                ('momentum_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('momentum_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
                ('macd_divergence', models.BooleanField(default=False, verbose_name='واگرایی در MACD')),
                ('macd_hidden_divergence', models.BooleanField(default=False, verbose_name='واگرایی مخفی در MACD')),
                ('macd_trend_breakout', models.BooleanField(default=False, verbose_name='شکست خط روند در MACD')),
                ('macd_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('macd_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
                ('stochastic_oversold', models.BooleanField(default=False, verbose_name='اشباع فروش در Stochastic')),
                ('stochastic_overbought', models.BooleanField(default=False, verbose_name='اشباع خرید در Stochastic')),
                ('stochastic_bullish_breakout', models.BooleanField(default=False, verbose_name='شکست صعودی در Stochastic')),
                ('stochastic_bearish_breakout', models.BooleanField(default=False, verbose_name='شکست نزولی در Stockastic')),
                ('atr', models.TextField(verbose_name='ATR')),
                ('atr_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('atr_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
                ('atx', models.TextField(verbose_name='ATX')),
                ('atx_signal', models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی')),
                ('atx_timeframe', models.CharField(choices=[('M5', 'M5'), ('M15', 'M15'), ('M30', 'M30'), ('H1', 'H1'), ('H4', 'H4'), ('D1', 'D1'), ('W1', 'W1')], max_length=3, verbose_name='تایم\u200cفریم')),
            ],
            options={
                'verbose_name': 'آنالیز Classic',
                'verbose_name_plural': 'آنالیزهای Classic',
            },
        ),
        migrations.AlterModelOptions(
            name='ptaanalysis',
            options={'verbose_name': 'آنالیز PTA', 'verbose_name_plural': 'آنالیز\u200cهای PTA'},
        ),
    ]
