# Generated by Django 3.1.2 on 2021-03-24 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0006_auto_20210324_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='classic_analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signal', to='cfd.classicanalysis', verbose_name='تحلیل Classic'),
        ),
    ]
