# Generated by Django 3.1.2 on 2021-03-24 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0007_signal_classic_analysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicanalysis',
            name='atr_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='atx_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='candle_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='intetrmediate_trend_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='macd_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='major_trend_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='momentum_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='moving_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='pattern_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='pivot_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='rsi_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='time_divergent_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], max_length=3, verbose_name='تایم\u200cفریم'),
        ),
    ]
