# Generated by Django 3.1.2 on 2021-03-25 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0009_auto_20210324_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='asset',
            field=models.CharField(choices=[('EUR/AUD', 'EUR/AUD'), ('EUR/USD', 'EUR/USD'), ('EUR/GBP', 'EUR/GBP'), ('USD/JPY', 'USD/JPY'), ('USD/CAD', 'USD/CAD'), ('AUD/CHF', 'AUD/CHF'), ('GBP/NZD', 'GBP/NZD'), ('BTC/USDT', 'BTC/USDT'), ('ETH/USDT', 'ETH/USDT'), ('TRX/USDT', 'TRX/USDT'), ('ADA/USDT', 'ADA/USDT')], default='EUR/USD', max_length=10, verbose_name='دارایی'),
        ),
    ]
