# Generated by Django 3.1.2 on 2021-03-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0010_auto_20210325_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('running', 'در حال اجرا'), ('done', 'انجام شده'), ('canceled', 'لغو شده')], default='running', max_length=8, verbose_name='وضعیت'),
        ),
    ]
