# Generated by Django 3.1.2 on 2021-03-28 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0011_signal_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='status',
            field=models.CharField(choices=[('running', 'در حال اجرا'), ('filled', 'انجام شده'), ('canceled', 'لغو شده')], default='running', max_length=8, verbose_name='وضعیت'),
        ),
    ]
