# Generated by Django 3.1.2 on 2021-03-28 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0012_auto_20210328_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='lot',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='حجم ورود'),
        ),
    ]
