# Generated by Django 3.1.2 on 2021-03-28 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0013_auto_20210328_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='result_dollar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7, verbose_name='سود/ضرر نهایی (دلار)'),
        ),
    ]
