# Generated by Django 3.1.2 on 2021-03-28 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0016_auto_20210328_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='canceld_datetime',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ و زمان لغو معامله'),
        ),
    ]
