# Generated by Django 3.1.2 on 2021-03-28 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0017_signal_canceld_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signal',
            old_name='canceld_datetime',
            new_name='canceled_datetime',
        ),
    ]
