# Generated by Django 3.1.2 on 2021-03-30 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfd', '0018_auto_20210328_1254'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classic_analysis', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
        migrations.AddField(
            model_name='ptaanalysis',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pta_analysis', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
