# Generated by Django 3.1.2 on 2021-03-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0020_classicanalysis_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicanalysis',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
