# Generated by Django 3.1.2 on 2021-03-30 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0021_classicanalysis_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classicanalysis',
            old_name='intetrmediate_trend',
            new_name='intermediate_trend',
        ),
        migrations.RenameField(
            model_name='classicanalysis',
            old_name='intetrmediate_trend_signal',
            new_name='intermediate_trend_signal',
        ),
        migrations.RenameField(
            model_name='classicanalysis',
            old_name='intetrmediate_trend_timeframe',
            new_name='intermediate_trend_timeframe',
        ),
    ]
