# Generated by Django 3.1.2 on 2021-03-31 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0025_auto_20210330_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicanalysis',
            name='candle',
            field=models.TextField(blank=True, null=True, verbose_name='کندل\u200cشناسی'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='eliot_signal',
            field=models.CharField(blank=True, choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, null=True, verbose_name='سیگنال دریافتی'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='fibo_correction',
            field=models.CharField(blank=True, choices=[('74', '74%'), ('61', '61.8%'), ('50', '50%'), ('38', '38.2%'), ('23', '23.6%')], max_length=2, null=True, verbose_name='اصلاح فیبوناچی'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='fibo_target',
            field=models.CharField(blank=True, choices=[('127', '127%'), ('150', '150%'), ('161', '161.8%'), ('200', '200%'), ('261', '261.8%'), ('423', '423.6%')], max_length=3, null=True, verbose_name='هدف فیبوناچی'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='intermediate_trend',
            field=models.CharField(choices=[('bl', 'صعودی'), ('br', 'نزولی'), ('sd', 'رنج')], default='bl', max_length=2, verbose_name='روند میان\u200cمدت'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='major_trend',
            field=models.CharField(choices=[('bl', 'صعودی'), ('br', 'نزولی'), ('sd', 'رنج')], default='bl', max_length=2, verbose_name='روند اصلی'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='pattern',
            field=models.CharField(choices=[('sy_tri', 'مثلث متقارن'), ('ds_tri', 'مثلث نزولی'), ('as_tri', 'مثلث صعودی'), ('ds_wdg', 'کنج نزولی'), ('as_wdg', 'کنج صعودی'), ('hd_sh', 'سر و شانه'), ('do_top', 'دو سقف'), ('do_btm', 'دو کف'), ('tr_top', 'سه سقف'), ('tr_btm', 'سه کف'), ('chnl', 'کانال'), ('flag', 'پرچم'), ('none', 'بدون الگو')], default='none', max_length=8, verbose_name='الگو'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='pivot',
            field=models.CharField(choices=[('d', 'روزانه'), ('w', 'هفتگی'), ('m', 'ماهیانه'), ('n', 'بدون Pivot')], default='n', max_length=1, verbose_name='خطوط Pivot'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='result_image_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='تصویر نهایی'),
        ),
    ]
