# Generated by Django 3.1.2 on 2021-03-31 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0026_auto_20210331_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicanalysis',
            name='candle_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='fibo_correction',
            field=models.CharField(choices=[('nc', 'بدون اصلاح'), ('23', '23.6%'), ('38', '38.2%'), ('50', '50%'), ('61', '61.8%'), ('74', '74%')], default='nc', max_length=2, verbose_name='اصلاح فیبوناچی'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='fibo_target',
            field=models.CharField(choices=[('nt', 'بدون هدف'), ('127', '127%'), ('150', '150%'), ('161', '161.8%'), ('200', '200%'), ('261', '261.8%'), ('423', '423.6%')], default='nt', max_length=3, verbose_name='هدف فیبوناچی'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='intermediate_trend_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='macd_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='major_trend_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1D', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='momentum_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='moving_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='pattern_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='pivot',
            field=models.CharField(choices=[('n', 'بدون Pivot'), ('d', 'روزانه'), ('w', 'هفتگی'), ('m', 'ماهیانه')], default='n', max_length=1, verbose_name='خطوط Pivot'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='pivot_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='rsi_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='time_divergent_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
    ]
