# Generated by Django 3.1.2 on 2021-03-31 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0028_auto_20210331_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classicanalysis',
            name='eliot',
            field=models.CharField(choices=[('nwv', 'بدون موج'), ('wv1', 'موج اول'), ('wv2', 'موج دوم'), ('wv3', 'موج سوم'), ('wv4', 'موج چهارم'), ('wv5', 'موج پنجم'), ('wva', 'موج A'), ('wvb', 'موج B'), ('wvc', 'موج C')], max_length=3, verbose_name='موج\u200cهای الیوت'),
        ),
    ]
