# Generated by Django 3.1.2 on 2021-04-01 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0030_auto_20210331_1839'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='نام دارایی')),
            ],
            options={
                'verbose_name': 'دارایی',
                'verbose_name_plural': 'دارایی\u200cها',
            },
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='moving',
            field=models.TextField(blank=True, null=True, verbose_name='میانگین متحرک'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='asset',
            field=models.CharField(max_length=10, verbose_name='دارایی'),
        ),
    ]
