# Generated by Django 3.1.2 on 2021-04-01 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0032_auto_20210401_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='lot',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='حجم ورود'),
        ),
    ]
