# Generated by Django 3.1.2 on 2021-04-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0033_auto_20210401_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicanalysis',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='title',
            field=models.CharField(default='adsf', max_length=70, verbose_name='عنوان'),
        ),
    ]
