# Generated by Django 3.1.2 on 2021-04-05 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0036_auto_20210405_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicanalysis',
            name='tradingview_url',
            field=models.URLField(blank=True, max_length=300, null=True, verbose_name='آدرس تحلیل در TradingView'),
        ),
    ]
