# Generated by Django 3.1.2 on 2021-04-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0037_classicanalysis_tradingview_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicanalysis',
            name='support_resistance1_from',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='شروع حمایت و مقاومت اوم'),
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='support_resistance1_to',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='پایان حمایت و مقاومت اوم'),
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='support_resistance2_from',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='شروع حمایت و مقاومت دوم'),
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='support_resistance2_to',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='پایان حمایت و مقاومت دوم'),
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='support_resistance3_from',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='شروع حمایت و مقاومت سوم'),
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='support_resistance3_to',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='پایان حمایت و مقاومت سوم'),
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='support_resistance_signal',
            field=models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی'),
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='support_resistance_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='momentum_divergence',
            field=models.BooleanField(default=False, verbose_name='واگرایی'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='momentum_hidden_divergence',
            field=models.BooleanField(default=False, verbose_name='واگرایی مخفی'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='momentum_overbought',
            field=models.BooleanField(default=False, verbose_name='اشباع خرید'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='momentum_oversold',
            field=models.BooleanField(default=False, verbose_name='اشباع فروش'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='momentum_trend_breakout',
            field=models.BooleanField(default=False, verbose_name='شکست خط روند'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='rsi_divergence',
            field=models.BooleanField(default=False, verbose_name='واگرایی'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='rsi_hidden_divergence',
            field=models.BooleanField(default=False, verbose_name='واگرایی مخفی'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='rsi_overbought',
            field=models.BooleanField(default=False, verbose_name='اشباع خرید'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='rsi_oversold',
            field=models.BooleanField(default=False, verbose_name='اشباع فروش'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='rsi_trend_breakout',
            field=models.BooleanField(default=False, verbose_name='شکست خط روند'),
        ),
    ]
