# Generated by Django 3.1.2 on 2021-04-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0038_auto_20210405_1536'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classicanalysis',
            old_name='support_resistance_timeframe',
            new_name='support_resistance1_timeframe',
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='support_resistance2_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='support_resistance3_timeframe',
            field=models.CharField(choices=[('5M', 'M5'), ('15M', 'M15'), ('30M', 'M30'), ('1H', 'H1'), ('4H', 'H4'), ('1D', 'D1'), ('1W', 'W1')], default='1H', max_length=3, verbose_name='تایم\u200cفریم'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='support_resistance1_from',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='شروع حمایت و مقاومت اول'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='support_resistance1_to',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=11, null=True, verbose_name='پایان حمایت و مقاومت اول'),
        ),
    ]
