# Generated by Django 3.1.2 on 2021-04-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0040_auto_20210408_0535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classicanalysis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='ptaanalysis',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
