# Generated by Django 3.1.2 on 2021-05-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0043_signal_self_entered'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptaanalysis',
            name='entrance',
            field=models.CharField(choices=[('fast', 'FAST'), ('dcnt', 'DISCOUNT')], default='dcnt', max_length=4, verbose_name='روش ورود'),
        ),
        migrations.AlterField(
            model_name='ptaanalysis',
            name='pattern',
            field=models.CharField(blank=True, choices=[('up_tri', 'مثلث صعودی'), ('dw_tri', 'مثلث نزولی'), ('rct', 'مستطیل'), ('h_sh', 'سر و شانه'), ('d_top', 'دو سقف'), ('d_btm', 'دو کف')], max_length=8, null=True, verbose_name='الگوی نمودار'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='self_entered',
            field=models.BooleanField(default=True, verbose_name='وارد شده\u200cاید؟'),
        ),
    ]
