# Generated by Django 3.1.2 on 2021-05-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0045_auto_20210512_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classicanalysis',
            name='macd_signal',
        ),
        migrations.RemoveField(
            model_name='classicanalysis',
            name='momentum_signal',
        ),
        migrations.RemoveField(
            model_name='classicanalysis',
            name='rsi_signal',
        ),
        migrations.RemoveField(
            model_name='classicanalysis',
            name='stochastic_signal',
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='momentum_family_signal',
            field=models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی اوسیلاتور'),
        ),
    ]
