# Generated by Django 3.1.2 on 2021-05-12 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0046_auto_20210512_1544'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptaanalysis',
            name='candle_pressure',
            field=models.BooleanField(default=False, verbose_name='فشارخوانی'),
        ),
    ]
