# Generated by Django 3.1.2 on 2021-05-13 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0048_classicanalysis_trend_lilne'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classicanalysis',
            old_name='trend_lilne',
            new_name='trend_line',
        ),
    ]
