# Generated by Django 3.1.2 on 2021-05-13 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0049_auto_20210513_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicanalysis',
            name='trend_line_signal',
            field=models.CharField(choices=[('by', 'خرید'), ('sl', 'فروش'), ('nt', 'خنثی')], default='nt', max_length=2, verbose_name='سیگنال دریافتی'),
        ),
    ]
