# Generated by Django 3.1.2 on 2021-06-23 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0050_classicanalysis_trend_line_signal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classicanalysis',
            options={'ordering': ['-datetime'], 'verbose_name': 'آنالیز Classic', 'verbose_name_plural': 'آنالیزهای Classic'},
        ),
        migrations.AlterModelOptions(
            name='signal',
            options={'ordering': ['-result_datetime'], 'verbose_name': 'سیگنال', 'verbose_name_plural': 'سیگنال\u200cها'},
        ),
    ]
