# Generated by Django 3.1.2 on 2021-06-24 14:36

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_remove_team_dmo_manager'),
        ('cfd', '0051_auto_20210623_2144'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='signal',
            managers=[
                ('signals', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='classicanalysis',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classic_analysis', to='team.team', verbose_name='تیم'),
        ),
        migrations.AddField(
            model_name='ptaanalysis',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pta_analysis', to='team.team', verbose_name='تیم'),
        ),
        migrations.AddField(
            model_name='signal',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signals', to='team.team', verbose_name='تیم'),
        ),
    ]
