# Generated by Django 3.1.2 on 2021-08-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0053_signalevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signalevent',
            name='event_type',
            field=models.CharField(choices=[('open', 'باز کردن سیگنال'), ('close', 'بستن'), ('cancel', 'لغو سیگنال'), ('change_sl', 'حد ضرر باز شده'), ('change_tp', 'حد سود باز شده'), ('dec_lot', 'کاهش حجم ورود'), ('inc_lot', 'افزایش حجم ورود')], default='open', max_length=10, verbose_name='نوع رخداد'),
        ),
    ]
