# Generated by Django 3.1.2 on 2022-02-02 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0057_evaluation_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='classicanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('live', 'Live'), ('demo', 'Demo'), ('btst', 'Back Test')], default='live', max_length=4, verbose_name='نوع سیگنال'),
        ),
        migrations.AddField(
            model_name='ptaanalysis',
            name='analysis_type',
            field=models.CharField(choices=[('live', 'Live'), ('demo', 'Demo'), ('btst', 'Back Test')], default='live', max_length=4, verbose_name='نوع سیگنال'),
        ),
    ]
