# Generated by Django 3.1.2 on 2022-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0058_auto_20220202_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='signal',
            name='signal_type',
            field=models.CharField(choices=[('live', 'Live'), ('demo', 'Demo'), ('btst', 'Back Test')], default='live', max_length=4, verbose_name='نوع سیگنال'),
        ),
    ]
