# Generated by Django 3.1.2 on 2022-03-27 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0059_signal_signal_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classicanalysis',
            name='analysis_type',
        ),
        migrations.RemoveField(
            model_name='ptaanalysis',
            name='analysis_type',
        ),
    ]
