# Generated by Django 3.1.2 on 2022-04-12 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0060_auto_20220327_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptaanalysis',
            name='impulsive_direction',
            field=models.CharField(blank=True, choices=[('rg', 'رنج'), ('up', 'صعودی'), ('dw', 'نزولی')], max_length=2, null=True, verbose_name='جهت روند'),
        ),
    ]
