# Generated by Django 3.1.2 on 2022-04-14 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('cfd', '0061_auto_20220412_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptaanalysis',
            name='desc',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='signal',
            name='analysis_id',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='signal',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='contenttypes.contenttype'),
        ),
    ]
