# Generated by Django 3.1.2 on 2022-04-16 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0062_auto_20220415_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signal',
            name='classic_analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfd.classicanalysis', verbose_name='تحلیل Classic'),
        ),
        migrations.AlterField(
            model_name='signal',
            name='pta_analysis',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cfd.ptaanalysis', verbose_name='تحلیل PTA'),
        ),
    ]
