# Generated by Django 3.1.2 on 2022-04-16 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0063_auto_20220416_2218'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signal',
            name='classic_analysis',
        ),
        migrations.RemoveField(
            model_name='signal',
            name='pta_analysis',
        ),
    ]
