# Generated by Django 3.1.2 on 2022-04-24 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0018_team_discord_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cfd', '0064_auto_20220416_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolumeProfileAnalysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='ولیوم پروفایل', max_length=100, null=True, verbose_name='عنوان')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('image_url', models.URLField(max_length=300, null=True)),
                ('environmental_condition', models.CharField(choices=[('gd', 'خوب'), ('bd', 'ضعیف')], default='gd', max_length=2, verbose_name='شرایط محیطی')),
                ('mental_condition', models.CharField(choices=[('gd', 'خوب'), ('bd', 'ضعیف')], default='gd', max_length=2, verbose_name='شرایط روحی')),
                ('checked_forex_factory', models.BooleanField(default=True, verbose_name='فارکس فکتوری بررسی شده؟')),
                ('time_session', models.CharField(choices=[('ny', 'نیویورک'), ('sy', 'سیدنی'), ('tk', 'توکیو'), ('ld', 'لندن'), ('ff', 'فرانک فرت')], default='ny', max_length=2, verbose_name='تایم\u200c معاملاتی')),
                ('time_session_is_suitable', models.BooleanField(default=False, verbose_name='تایم\u200c معاملاتی مناسب است؟')),
                ('fundamental_analysis', models.CharField(choices=[('y', 'بله'), ('n', 'خیر')], default='y', max_length=2, verbose_name='آنالیز فاندامنتال')),
                ('technical_analysis', models.CharField(choices=[('y', 'بله'), ('n', 'خیر')], default='y', max_length=2, verbose_name='آنالیز تکنیکال')),
                ('tradingview_url', models.URLField(blank=True, max_length=300, null=True, verbose_name='آدرس تحلیل در TradingView')),
                ('team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vp_analysis', to='team.team', verbose_name='تیم')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vp_analysis', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'ولیوم پروفایل',
                'verbose_name_plural': 'ولیوم پروفایل',
                'ordering': ('-datetime',),
            },
        ),
    ]
