# Generated by Django 3.1.2 on 2022-04-24 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0065_volumeprofileanalysis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptaanalysis',
            name='title',
            field=models.CharField(default='تحلیل PTA', max_length=100, null=True, verbose_name='عنوان'),
        ),
    ]
