# Generated by Django 3.1.2 on 2022-04-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cfd', '0066_auto_20220424_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='volumeprofileanalysis',
            name='major_trend',
            field=models.CharField(blank=True, choices=[('up', 'صعودی'), ('down', 'نزولی'), ('side', 'رنج')], default='side', max_length=4, null=True, verbose_name='روند اصلی'),
        ),
        migrations.AddField(
            model_name='volumeprofileanalysis',
            name='trade_time',
            field=models.CharField(blank=True, choices=[('daily', 'روزانه'), ('short', 'کوتاه مدت'), ('mid', 'میان مدت'), ('long', 'بلند مدت')], default='daily', max_length=5, null=True, verbose_name='تایم معاملاتی'),
        ),
        migrations.AddField(
            model_name='volumeprofileanalysis',
            name='trade_time_trend',
            field=models.CharField(blank=True, choices=[('up', 'صعودی'), ('down', 'نزولی'), ('side', 'رنج')], default='side', max_length=4, null=True, verbose_name='روند تایم معامله'),
        ),
    ]
