# Generated by Django 3.1.2 on 2021-02-26 18:51

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dmo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal', models.CharField(max_length=200, verbose_name='هدف')),
                ('month', models.PositiveSmallIntegerField(default=12, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='ماه')),
                ('year', models.PositiveSmallIntegerField(default=1399, validators=[django.core.validators.MinValueValidator(1390), django.core.validators.MaxValueValidator(1499)], verbose_name='سال')),
                ('success_slogan', models.CharField(blank=True, max_length=200, null=True, verbose_name='شعار موفقیت')),
                ('failure_slogan', models.CharField(blank=True, max_length=200, null=True, verbose_name='شعار شکست')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dmo_set', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'DMO',
                'verbose_name_plural': 'DMOs',
            },
        ),
        migrations.CreateModel(
            name='Microaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('dmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='microactions', to='dmo.dmo', verbose_name='Dmo')),
            ],
            options={
                'verbose_name': 'میکرواکشن',
                'verbose_name_plural': 'میکرواکشن\u200cها',
            },
        ),
        migrations.CreateModel(
            name='DmoDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='روز')),
                ('done', models.BooleanField(verbose_name='انجام شده')),
                ('comment', models.CharField(blank=True, max_length=200, null=True, verbose_name='توضیحات')),
                ('dmo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='dmo.dmo', verbose_name='Dmo')),
            ],
            options={
                'verbose_name': 'روز Dmo',
                'verbose_name_plural': 'روزهای Dmo',
            },
        ),
    ]
