# Generated by Django 3.1.2 on 2021-03-03 12:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmoday',
            name='day',
            field=models.IntegerField(default=13, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='روز'),
        ),
    ]
