# Generated by Django 3.1.2 on 2021-03-04 06:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmo', '0002_auto_20210303_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmoday',
            name='day',
            field=models.IntegerField(default=14, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(30)], verbose_name='روز'),
        ),
    ]
