# Generated by Django 3.1.2 on 2021-03-05 04:42

import django.core.validators
from django.db import migrations, models
import dmo.models


class Migration(migrations.Migration):

    dependencies = [
        ('dmo', '0003_auto_20210304_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmo',
            name='month',
            field=models.PositiveSmallIntegerField(default=dmo.models.current_month, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='ماه'),
        ),
        migrations.AlterField(
            model_name='dmo',
            name='year',
            field=models.PositiveSmallIntegerField(default=dmo.models.current_year, validators=[django.core.validators.MinValueValidator(1390), django.core.validators.MaxValueValidator(1499)], verbose_name='سال'),
        ),
        migrations.AlterField(
            model_name='dmoday',
            name='day',
            field=models.IntegerField(default=dmo.models.DmoDay.current_day, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(dmo.models.DmoDay.current_month_days)], verbose_name='روز'),
        ),
    ]
