# Generated by Django 3.1.2 on 2021-03-14 16:05

from django.db import migrations, models
import dmo.model_fields


class Migration(migrations.Migration):

    dependencies = [
        ('dmo', '0004_auto_20210305_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmo',
            name='color',
            field=dmo.model_fields.ColorField(default='#4287f5', max_length=10, verbose_name='رنگ'),
        ),
        migrations.AddField(
            model_name='dmo',
            name='dmo_type',
            field=models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], default='private', max_length=10, verbose_name='نوع DMO'),
        ),
    ]
