# Generated by Django 3.2 on 2021-04-08 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmo', '0005_auto_20210314_1935'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='dmoday',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='microaction',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
