# Generated by Django 3.1.2 on 2021-05-11 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dmo', '0007_auto_20210420_1250'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dmo',
            name='failure_slogan',
        ),
        migrations.RemoveField(
            model_name='dmo',
            name='success_slogan',
        ),
    ]
