# Generated by Django 3.1.2 on 2021-06-22 17:54

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0013_auto_20210513_1850'),
        ('dmo', '0008_auto_20210511_1538'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='dmo',
            managers=[
                ('contents', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name='dmo',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dmos', to='team.team', verbose_name='تیم'),
        ),
        migrations.AlterField(
            model_name='dmo',
            name='dmo_type',
            field=models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی'), ('team', 'تیمی')], default='private', max_length=10, verbose_name='نوع DMO'),
        ),
    ]
