# Generated by Django 3.1.2 on 2021-06-23 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dmo', '0009_auto_20210622_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='dmoday',
            name='user_locked',
            field=models.BooleanField(default=False, verbose_name='قفل کاربر'),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dmo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dmo.dmo', verbose_name='DMO')),
                ('dmo_manager', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مدیر DMO')),
            ],
            options={
                'verbose_name': 'تنظیم DMO',
                'verbose_name_plural': 'تنظیمات DMO',
            },
        ),
    ]
