# Generated by Django 3.1.2 on 2021-06-23 17:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0015_remove_team_dmo_manager'),
        ('dmo', '0010_auto_20210623_2144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='dmo',
        ),
        migrations.AddField(
            model_name='setting',
            name='team',
            field=models.OneToOneField(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='dmo_settings', to='team.team', verbose_name='تیم'),
            preserve_default=False,
        ),
    ]
