# Generated by Django 3.1.2 on 2021-12-23 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmo', '0012_auto_20210623_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='discord_webhook',
            field=models.URLField(blank=True, verbose_name='Webhook دیسکورد'),
        ),
    ]
