GENERIC_MODEL_FORM = 'generic_model_multiform.html'
GENERIC_MODEL_LIST = 'generic_model_list.html'
GENERIC_TEXT_EDITOR = 'generic_text_editor.html'
GENERIC_MESSAGE = 'message.html'
HTTP403PAGE = 'http403.html'
MY_TEAMS_TEMPLATE = 'gentelella/my_teams.html'
PROCEEDINGS_TEMPLATE = 'gentelella/proceedings.html'
PARTICIPATE_TEMPLATE = 'gentelella/participate.html'
