# Generated by Django 3.2 on 2021-04-11 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام تیم')),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='رهبر')),
                ('users', models.ManyToManyField(related_name='team_set', to=settings.AUTH_USER_MODEL, verbose_name='اعضا')),
            ],
            options={
                'verbose_name': 'تیم',
                'verbose_name_plural': 'تیم\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_datetime', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نظرسنجی')),
                ('due_datetime', models.DateTimeField(verbose_name='مهلت')),
                ('vote_type', models.CharField(choices=[('pub', 'عمومی'), ('sec', 'مخفی')], default='pub', max_length=3, verbose_name='نوع نظرسنجی')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='team.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'نظرسنجی',
                'verbose_name_plural': 'نظرسنجی\u200cها',
            },
        ),
        migrations.CreateModel(
            name='VoteChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.CharField(max_length=200, verbose_name='گزینه')),
                ('vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='team.vote', verbose_name='نظرسنجی')),
            ],
            options={
                'verbose_name': 'گزینه',
                'verbose_name_plural': 'گزینه\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان جلسه')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='team.team', verbose_name='تیم')),
            ],
            options={
                'verbose_name': 'جلسه',
                'verbose_name_plural': 'جلسات',
            },
        ),
        migrations.CreateModel(
            name='UserVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voted_date', models.DateTimeField(auto_created=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('user_choice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_votes', to='team.votechoice', verbose_name='انتخاب کاربر')),
            ],
            options={
                'verbose_name': 'نظر کاربر',
                'verbose_name_plural': 'نظرات کاربران',
                'unique_together': {('user', 'user_choice')},
            },
        ),
        migrations.CreateModel(
            name='MeetingSigature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_date', models.DateTimeField(auto_created=True, verbose_name='تاریخ مشاهده')),
                ('read', models.BooleanField(verbose_name='خوانده شده')),
                ('sign_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ امضا')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signatures', to='team.meeting', verbose_name='جلسه')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signatures', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'امضا جلسه',
                'verbose_name_plural': 'امضا جلسات',
                'unique_together': {('meeting', 'user')},
            },
        ),
    ]
