# Generated by Django 3.2 on 2021-04-11 17:32

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 11, 22, 2, 23, 715672), verbose_name='تاریخ جلسه'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='meeting',
            name='proceedings',
            field=models.TextField(blank=True, null=True, verbose_name='صورتجلسه'),
        ),
        migrations.AlterField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams_as_leader', to=settings.AUTH_USER_MODEL, verbose_name='رهبر'),
        ),
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='اعضا'),
        ),
        migrations.CreateModel(
            name='TeamInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_datetime', models.DateTimeField(auto_created=True)),
                ('action', models.CharField(choices=[('ac', 'پذیرفتن'), ('rj', 'رد کردن'), ('n', 'بدون عمل')], default='n', max_length=2)),
                ('action_datetime', models.DateTimeField(null=True, verbose_name='تاریخ عملیات')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='team.team', verbose_name='تیم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_invitations', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'دعوتنامه تیم',
                'verbose_name_plural': 'دعوتنامه\u200cهای تیم',
            },
        ),
    ]
