# Generated by Django 3.2 on 2021-04-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210411_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'permissions': (('manage_team', 'مدیریت تیم'),), 'verbose_name': 'تیم', 'verbose_name_plural': 'تیم\u200cها'},
        ),
    ]
