# Generated by Django 3.2 on 2021-04-13 06:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0003_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='users',
            field=models.ManyToManyField(null=True, related_name='teams', to=settings.AUTH_USER_MODEL, verbose_name='اعضا'),
        ),
    ]
