# Generated by Django 3.2 on 2021-04-13 09:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0005_alter_team_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='تاریخ جلسه'),
        ),
    ]
