# Generated by Django 3.2 on 2021-04-13 12:03

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0006_alter_meeting_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='proceedings',
            field=django_quill.fields.QuillField(blank=True, null=True, verbose_name='صورتجلسه'),
        ),
    ]
