# Generated by Django 3.2 on 2021-04-13 15:33

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0008_auto_20210413_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now, verbose_name='تاریخ')),
                ('attendance_type', models.CharField(choices=[('p', 'حاضر'), ('a', 'عدم حضور'), ('l', 'مرخصی کامل'), ('h', 'مرخصی ساعتی')], default='a', max_length=1, verbose_name='نوع حضور')),
                ('leave_hours', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='مدت مرخصی ساعتی')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='team.team', verbose_name='تیم')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'حضور و غیاب',
                'verbose_name_plural': 'حضور و غیاب\u200cها',
                'unique_together': {('user', 'date')},
            },
        ),
    ]
