# Generated by Django 3.2 on 2021-04-14 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0009_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='publish_datetime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
