# Generated by Django 3.1.2 on 2021-05-13 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0012_auto_20210513_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='attendance_type',
            field=models.CharField(choices=[('p', 'حاضر'), ('a', 'عدم حضور'), ('l', 'مرخصی کامل'), ('h', 'مرخصی (دقیقه)')], default='a', max_length=1, verbose_name='نوع حضور'),
        ),
    ]
