# Generated by Django 3.1.2 on 2021-06-23 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('team', '0013_auto_20210513_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='dmo_manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='مدیر DMO'),
        ),
    ]
