# Generated by Django 3.1.2 on 2021-06-24 16:09

from django.db import migrations, models
import team.models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0016_team_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='avatar',
            field=models.ImageField(blank=True, default='team/avatar.png', max_length=300, null=True, upload_to='team/avatars', validators=[team.models.file_size_validator], verbose_name='تصویر نمایه'),
        ),
    ]
