# Generated by Django 3.1.2 on 2021-12-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0017_auto_20210624_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='discord_url',
            field=models.URLField(blank=True, null=True, verbose_name='آدرس دیسکورد'),
        ),
    ]
