# Generated by Django 3.1.2 on 2022-05-21 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmo', '0013_setting_discord_webhook'),
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolistitem',
            name='dmo_day',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todo_list_item', to='dmo.dmoday', verbose_name='دمو'),
        ),
    ]
