# Generated by Django 3.1.2 on 2022-05-21 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0002_todolistitem_dmo_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolistitem',
            name='desc',
            field=models.TextField(blank=True, verbose_name='توضیحات'),
        ),
    ]
