# Generated by Django 3.1.2 on 2020-11-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20201116_2118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('edit_permission', 'Edit user or group permissions'), ('view_user', 'View users and profiles'), ('add_user', 'Create users and profiles'), ('edit_user', 'Edit users and profiles'), ('edit_user_pass', 'Change user password'), ('delete_user', 'Delete users and profiles'), ('view_group', 'View groups and memberships'), ('add_group', 'Create groups'), ('edit_group', 'Edit groups'), ('group_membership', 'Edit group memberships'), ('delete_group', 'Delete groups')], 'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل\u200cها'},
        ),
    ]
