# Generated by Django 3.1.2 on 2020-11-23 14:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201117_1414'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsetting',
            options={'verbose_name': 'تنظیمات حساب', 'verbose_name_plural': 'تنظیمات حساب'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('edit_permission', 'ویرایش کاربران یا گروه\u200cها'), ('view_user', 'مشاهده کاربران و پروفایل\u200cها'), ('add_user', 'ایجاد کاربران و پروفایل\u200cها'), ('edit_user', 'ویرایش کاربران و پروفایل\u200cها'), ('edit_user_pass', 'تغییر رمز کاربران'), ('delete_user', 'حذف کاربران و پروفایل\u200cها'), ('view_group', 'مشاهده گروه\u200cها و اعضا'), ('add_group', 'ایجاد گروه\u200cها'), ('edit_group', 'ویرایش گروه\u200cها'), ('group_membership', 'ویرایش اعضای گروه'), ('delete_group', 'حذف گروه\u200cها')], 'verbose_name': 'پروفایل', 'verbose_name_plural': 'پروفایل\u200cها'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'آدرس کاربر', 'verbose_name_plural': 'آدرس\u200cهای کاربر'},
        ),
        migrations.AddField(
            model_name='accountsetting',
            name='avatar_max_file_size',
            field=models.PositiveSmallIntegerField(default=2, verbose_name='حداکثر حجم مجاز آپلود تصویر نمایه'),
        ),
        migrations.AlterField(
            model_name='accountsetting',
            name='only_admin_can_login',
            field=models.BooleanField(default=False, verbose_name='اجازه ورود کاربران غیر مدیر'),
        ),
        migrations.AlterField(
            model_name='accountsetting',
            name='user_can_register',
            field=models.BooleanField(default=True, verbose_name='اجازه ثبت\u200cنام در سایت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, max_length=300, null=True, upload_to='account/avatars', validators=[accounts.models.file_size_validator], verbose_name='تصویر نمایه'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس'),
        ),
    ]
