# Generated by Django 3.1.2 on 2020-11-26 08:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20201123_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsetting',
            options={'permissions': [('edit_setting', 'ویرایش تنظیمات')], 'verbose_name': 'تنظیمات حساب', 'verbose_name_plural': 'تنظیمات حساب'},
        ),
        migrations.RemoveField(
            model_name='accountsetting',
            name='only_admin_can_login',
        ),
        migrations.AlterField(
            model_name='accountsetting',
            name='avatar_max_file_size',
            field=models.PositiveSmallIntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='حجم مجاز آپلود تصویر نمایه (مگابایت)'),
        ),
    ]
