# Generated by Django 3.1.2 on 2020-11-26 09:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0009_auto_20201126_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.CharField(max_length=300, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='phone',
            field=models.PositiveIntegerField(help_text='شماره تلفن را بدون صفر ابتدای آن وارد کنید', validators=[django.core.validators.MaxValueValidator(9999999999), django.core.validators.MinValueValidator(9000000000)], verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(max_length=10, verbose_name='کد پستی'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
