# Generated by Django 3.1.2 on 2020-11-29 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20201126_1349'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accountsetting',
            options={'permissions': [('edit_setting', 'ویرایش تنظیمات')], 'verbose_name': 'Account Settings', 'verbose_name_plural': 'Account Settings'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('edit_permission', 'Edit user or group permissions'), ('view_user', 'View users and profiles'), ('add_user', 'Create users and profiles'), ('edit_user', 'Edit users and profiles'), ('edit_user_pass', 'Change user password'), ('delete_user', 'Delete users and profiles'), ('view_group', 'View groups and memberships'), ('add_group', 'Create groups'), ('edit_group', 'Edit groups'), ('group_membership', 'Edit group memberships'), ('delete_group', 'Delete groups')], 'verbose_name': 'Profile', 'verbose_name_plural': 'Profiles'},
        ),
        migrations.AlterModelOptions(
            name='useraddress',
            options={'verbose_name': 'User Address', 'verbose_name_plural': 'User Addresses'},
        ),
    ]
