# Generated by Django 3.1.2 on 2021-01-13 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20201205_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='preferred_language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English'), ('ar', 'Arabic')], default='fa', max_length=5, verbose_name='زبان'),
        ),
    ]
