# Generated by Django 3.1.2 on 2021-05-11 11:32

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20210511_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='account/profile.png', max_length=300, upload_to='account/avatars', validators=[accounts.models.file_size_validator], verbose_name='تصویر نمایه'),
        ),
    ]
