# Generated by Django 3.1.2 on 2020-11-28 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='slug',
            field=models.SlugField(blank=True, null=True, verbose_name='نشانی (slug)'),
        ),
        migrations.AlterField(
            model_name='themepage',
            name='theme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='theme.theme', verbose_name='پوسته'),
        ),
        migrations.AlterField(
            model_name='themepagetype',
            name='page_type',
            field=models.CharField(choices=[('base', 'پایه'), ('blog', 'بلاگ'), ('post', 'پست'), ('search', 'جستجو'), ('cat', 'دسته\u200cبندی')], max_length=50, verbose_name='نوع صفحه'),
        ),
    ]
