# Generated by Django 3.1.2 on 2020-11-28 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_auto_20201128_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='themepage',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme_page', to='theme.themepage'),
        ),
    ]
