# Generated by Django 3.1.2 on 2020-11-28 15:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_themepage_base'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='themepage',
            name='base',
        ),
        migrations.AddField(
            model_name='page',
            name='base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='base_page', to='theme.page'),
        ),
    ]
