# Generated by Django 3.1.2 on 2020-11-28 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_auto_20201128_1918'),
    ]

    operations = [
        migrations.AddField(
            model_name='themepage',
            name='page_type',
            field=models.CharField(choices=[('base', 'پایه'), ('blog', 'بلاگ'), ('post', 'پست'), ('search', 'جستجو'), ('cat', 'دسته\u200cبندی')], default='blog', max_length=50, verbose_name='نوع صفحه'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ThemePageType',
        ),
    ]
