# Generated by Django 3.1.2 on 2020-11-29 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_auto_20201128_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='theme_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='theme.themepage', verbose_name='صفحه پوسته'),
        ),
    ]
