# Generated by Django 3.1.2 on 2020-12-03 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0013_auto_20201202_1641'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagecategory',
            options={'verbose_name': 'متغیر دسته\u200cبندی صفحه', 'verbose_name_plural': 'متغیرهای دسته\u200cبندی صفحه'},
        ),
        migrations.AlterModelOptions(
            name='pagemenu',
            options={'verbose_name': 'متغیر منو صفحه', 'verbose_name_plural': 'متغیرهای منو صفحه'},
        ),
        migrations.AlterModelOptions(
            name='pagetext',
            options={'verbose_name': 'متغیر متن صفحه', 'verbose_name_plural': 'متغیرهای متن صفحه'},
        ),
        migrations.AddField(
            model_name='theme',
            name='author_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل توسعه دهنده'),
        ),
        migrations.AddField(
            model_name='theme',
            name='author_name',
            field=models.CharField(default='Mohsen Hassani', max_length=200, verbose_name='توسعه دهنده'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='desc',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='theme', verbose_name='تصویر'),
        ),
        migrations.AddField(
            model_name='theme',
            name='website',
            field=models.URLField(blank=True, null=True, verbose_name='سایت'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subitems', to='theme.menuitem', verbose_name='آیتم والد'),
        ),
    ]
