# Generated by Django 3.1.2 on 2020-12-05 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0014_auto_20201203_1653'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='image',
        ),
    ]
