# Generated by Django 3.1.2 on 2020-12-05 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0015_remove_theme_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تصویر'),
        ),
    ]
