# Generated by Django 3.1.2 on 2020-12-07 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0016_theme_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hans-zh', 'Simplified Chinese')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagecategorycontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hans-zh', 'Simplified Chinese')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagemenucontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hans-zh', 'Simplified Chinese')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagetextcontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hans-zh', 'Simplified Chinese')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='تصویر'),
        ),
    ]
