# Generated by Django 3.1.2 on 2020-12-09 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_remove_postcategory_count'),
        ('theme', '0018_pagecategory_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagePost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_variable', models.CharField(max_length=100, verbose_name='نام متغیر پست')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_categories', to='theme.page', verbose_name='صفحه')),
            ],
            options={
                'verbose_name': 'متغیر پست صفحه',
                'verbose_name_plural': 'متغیرهای پست صفحه',
            },
        ),
        migrations.AlterField(
            model_name='pagecategory',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_posts', to='theme.page', verbose_name='صفحه'),
        ),
        migrations.CreateModel(
            name='PagePostContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hans-zh', 'Simplified Chinese')], max_length=10, verbose_name='زبان')),
                ('page_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='theme.pagepost', verbose_name='متغیر پست')),
                ('post_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست')),
            ],
            options={
                'verbose_name': 'محتوای متغیر پست',
                'verbose_name_plural': 'محتوای متغیرهای پست',
            },
        ),
    ]
