# Generated by Django 3.1.2 on 2020-12-11 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0020_auto_20201209_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='themepage',
            name='page_type',
            field=models.CharField(choices=[('base', 'پایه'), ('blog', 'بلاگ'), ('post', 'پست'), ('search', 'جستجو'), ('cat', 'دسته\u200cبندی'), ('custom', 'سفارشی')], max_length=50, verbose_name='نوع صفحه'),
        ),
    ]
