# Generated by Django 3.1.2 on 2020-12-11 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0002_auto_20201211_1255'),
        ('theme', '0021_auto_20201211_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_variable', models.CharField(max_length=100, verbose_name='نام متغیر')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_images', to='theme.page', verbose_name='صفحه')),
            ],
            options={
                'verbose_name': 'متغیر تصویر صفحه',
                'verbose_name_plural': 'متغیر\u200cهای تصویر صفحه',
            },
        ),
        migrations.CreateModel(
            name='PageImageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('hans-zh', 'Simplified Chinese')], max_length=10, verbose_name='زبان')),
                ('image_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_values', to='file.file', verbose_name='تصویر')),
                ('page_image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_images', to='theme.pageimage', verbose_name='متغیر تصویر')),
            ],
            options={
                'verbose_name': 'محتوای متغیر تصویر',
                'verbose_name_plural': 'محتوا\u200cهای متغیر تصویر',
            },
        ),
    ]
