# Generated by Django 3.1.2 on 2020-12-14 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0022_pageimage_pageimagecontent'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_variable', models.CharField(max_length=100, verbose_name='نام متغیر')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='page_links', to='theme.page', verbose_name='صفحه')),
            ],
            options={
                'verbose_name': 'متغیر لینک صفحه',
                'verbose_name_plural': 'متغیرهای لینک صفحه',
            },
        ),
        migrations.AlterField(
            model_name='menuitemcontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('zh-cn', 'Simplified Chinese')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagecategorycontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('zh-cn', 'Simplified Chinese')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pageimagecontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('zh-cn', 'Simplified Chinese')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagemenucontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('zh-cn', 'Simplified Chinese')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagepostcontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('zh-cn', 'Simplified Chinese')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagetextcontent',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('zh-cn', 'Simplified Chinese')], max_length=10, verbose_name='زبان'),
        ),
        migrations.CreateModel(
            name='PageLinkContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_value', models.CharField(max_length=500, verbose_name='محتوای لینک')),
                ('language', models.CharField(choices=[('en', 'English'), ('fa', 'Persian'), ('zh-cn', 'Simplified Chinese')], max_length=10, verbose_name='زبان')),
                ('page_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='theme.pagelink', verbose_name='متغیر لینک')),
            ],
            options={
                'verbose_name': 'محتوای متغیر لینک',
                'verbose_name_plural': 'محتوای متغیرهای لینک',
            },
        ),
    ]
