# Generated by Django 3.1.2 on 2020-12-14 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0023_auto_20201214_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='image',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تصویر'),
        ),
    ]
