# Generated by Django 3.1.2 on 2021-01-19 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_auto_20210119_1717'),
        ('file', '0002_auto_20201211_1255'),
        ('theme', '0025_auto_20210114_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagecategorycontent',
            name='category_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.category', verbose_name='دسته\u200cبندی'),
        ),
        migrations.AlterField(
            model_name='pageimagecontent',
            name='image_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='image_values', to='file.file', verbose_name='تصویر'),
        ),
        migrations.AlterField(
            model_name='pagelinkcontent',
            name='link_value',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='محتوای لینک'),
        ),
        migrations.AlterField(
            model_name='pagepostcontent',
            name='post_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post', verbose_name='پست'),
        ),
        migrations.AlterField(
            model_name='pagetextcontent',
            name='text_value',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='محتوای متنی'),
        ),
    ]
