# Generated by Django 3.1.2 on 2021-01-19 22:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0026_auto_20210119_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemenucontent',
            name='menu_content',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='theme.menu', verbose_name='منو'),
        ),
    ]
