# Generated by Django 3.1.2 on 2021-03-04 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0027_auto_20210120_0142'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
