# Generated by Django 3.1.2 on 2021-03-04 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0028_menuitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(default=111, unique=True, verbose_name='موقعیت'),
            preserve_default=False,
        ),
    ]
