# Generated by Django 3.1.2 on 2021-03-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0029_auto_20210304_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='order',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='موقعیت'),
        ),
    ]
