# Generated by Django 3.1.2 on 2021-03-06 16:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_keywords'),
        ('theme', '0030_auto_20210304_1015'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(verbose_name='آدرس صفحه')),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='blog.post', verbose_name='پست')),
                ('theme_page', models.ForeignKey(blank=True, limit_choices_to={'page_type': 'post', 'theme__is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custompages', to='theme.themepage', verbose_name='نوع صفحه')),
            ],
            options={
                'verbose_name': 'صفحه شخصی',
                'verbose_name_plural': 'صفحات شخصی',
            },
        ),
    ]
