# Generated by Django 3.1.2 on 2021-03-06 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0031_custompage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='theme_page',
            field=models.ForeignKey(blank=True, limit_choices_to={'theme__is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pages', to='theme.themepage', verbose_name='صفحه پوسته'),
        ),
        migrations.DeleteModel(
            name='CustomPage',
        ),
    ]
