# Generated by Django 3.1.2 on 2021-03-06 18:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_post_keywords'),
        ('theme', '0033_auto_20210306_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='blog.post', verbose_name='پست'),
        ),
    ]
