# Generated by Django 3.1.2 on 2021-03-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0034_page_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_title', models.CharField(max_length=200, verbose_name='عنوان سایت')),
                ('site_subtitle', models.CharField(max_length=500, verbose_name='زیرعنوان سایت')),
            ],
            options={
                'verbose_name': 'تنظیمات سایت',
                'verbose_name_plural': 'تنظیمات سایت',
            },
        ),
        migrations.CreateModel(
            name='ThemeSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primary_light_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ اصلی')),
                ('primary_bold_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ اصلی پررنگ')),
                ('primary_dark_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ اصلی تیره')),
                ('accend_light_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ فرعی')),
                ('accend_bold_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ فرعی پررنگ')),
                ('accend_dark_color', models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ فرعی تیره')),
            ],
            options={
                'verbose_name': 'تنظیمات پوسته',
                'verbose_name_plural': 'تنظیمات پوسته',
            },
        ),
    ]
