# Generated by Django 3.1.2 on 2021-03-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0035_sitesetting_themesetting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_subtitle',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='زیرعنوان سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان سایت'),
        ),
    ]
