# Generated by Django 3.1.2 on 2021-03-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0036_auto_20210313_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='home_page',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='صفحه اصلی سایت'),
        ),
    ]
