# Generated by Django 3.1.2 on 2021-03-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0037_sitesetting_home_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_subtitle',
            field=models.CharField(default=' ', max_length=500, verbose_name='زیرعنوان سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default=' ', max_length=200, verbose_name='عنوان سایت'),
        ),
    ]
