# Generated by Django 3.1.2 on 2021-03-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0039_auto_20210313_1822'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ThemeSetting',
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='accend_bold_color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ فرعی پررنگ'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='accend_dark_color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ فرعی تیره'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='accend_light_color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ فرعی'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_bold_color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ اصلی پررنگ'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_dark_color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ اصلی تیره'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='primary_light_color',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='رنگ اصلی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_subtitle',
            field=models.CharField(default='New Django-based CMS', max_length=500, verbose_name='زیرعنوان سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default='Robis', max_length=200, verbose_name='عنوان سایت'),
        ),
    ]
