# Generated by Django 3.1.2 on 2021-03-14 05:59

from django.db import migrations, models
import theme.models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0042_auto_20210313_1951'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShinyThing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', theme.models.ColorField(default='#ffffff', max_length=10)),
            ],
        ),
    ]
