# Generated by Django 3.1.2 on 2021-03-14 06:04

from django.db import migrations
import theme.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0043_shinything'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ShinyThing',
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='accend_bold_color',
            field=theme.fields.ColorField(blank=True, max_length=10, null=True, verbose_name='رنگ فرعی پررنگ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='accend_dark_color',
            field=theme.fields.ColorField(blank=True, max_length=10, null=True, verbose_name='رنگ فرعی تیره'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='accend_light_color',
            field=theme.fields.ColorField(blank=True, max_length=10, null=True, verbose_name='رنگ فرعی'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='primary_bold_color',
            field=theme.fields.ColorField(blank=True, max_length=10, null=True, verbose_name='رنگ اصلی پررنگ'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='primary_dark_color',
            field=theme.fields.ColorField(blank=True, max_length=10, null=True, verbose_name='رنگ اصلی تیره'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='primary_light_color',
            field=theme.fields.ColorField(blank=True, max_length=10, null=True, verbose_name='رنگ اصلی'),
        ),
    ]
