# Generated by Django 3.1.2 on 2021-04-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0044_auto_20210314_0934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitemcontent',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagecategorycontent',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pageimagecontent',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagelinkcontent',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagemenucontent',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagepostcontent',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=10, verbose_name='زبان'),
        ),
        migrations.AlterField(
            model_name='pagetextcontent',
            name='language',
            field=models.CharField(choices=[('fa', 'Persian'), ('en', 'English')], max_length=10, verbose_name='زبان'),
        ),
    ]
