# Generated by Django 3.1.2 on 2021-04-20 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0045_auto_20210420_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetting',
            name='site_subtitle',
            field=models.CharField(default='Team Management System', max_length=500, verbose_name='زیرعنوان سایت'),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='site_title',
            field=models.CharField(default='TeamChe', max_length=200, verbose_name='عنوان سایت'),
        ),
    ]
